
@startuml

scale 1

!include <C4/C4_Container>
!theme C4_superhero from <C4/themes>

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()
HIDE_STEREOTYPE()
!$lineFont = "#dbdbdb"
!$arrowFontSize = 2

AddElementTag("network", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#3867ba", $borderColor="#4c8dff", $legendText="Core Switch")
AddElementTag("bareMetal", $fontColor=$ELEMENT_FONT_COLOR, $bgColor="#2fb397", $borderColor="#4b9464", $legendText="Compute Node")
AddElementTag("service", $fontColor="#efefef", $bgColor="#5b5b5b", $borderColor="#1b1b1b", $legendText="Service")

AddElementTag("lxdContainer", $fontColor="#efefef", $bgColor="#3b3b3b", $borderColor="#1b1b1b", $legendText="LXD Container")
AddElementTag("region", $fontColor="#efefef", $bgColor="#5b5b5b", $borderColor="#1b1b1b", $legendText="Region Boundary")
AddRelTag("VLANMirror", $textColor=$lineFont, $lineColor=#red, $legendText="VLAN Mirror")
AddRelTag("Trunk", $textColor=$lineFont, $lineColor=#blue, $legendText="Trunk")
AddRelTag("VLANBridge", $textColor=$lineFont, $lineColor=#green, $legendText="VLAN Bridge")
AddRelTag("IntMirror", $textColor=$lineFont, $lineColor=#orange, $legendText="Interface Mirror")

skinparam linetype ortho
skinparam ParticipantPadding 60
skinparam svgDimensionStyle false

!$BOUNDARY_COLOR ?= "#4b4b4b"

Title "Miridor Network Diagram"

Person(user, "Miridor User")
System(backbone, "Research & Education Network", $tags="network")
Rel_D(user, backbone, "")

Boundary(yegBoundary, "Edmonton Datacenter", $tags="region")  {
  System(yegSwitch, "Distribution Switch", $tags="network")
    System(yegMiridor01, "LXD Host\nyeg-miridor-01", $tags="bareMetal")
    Rel_D(yegSwitch, yegMiridor01, "", $tags="VLANMirror")
    Rel_D(yegSwitch, yegMiridor01, "", $tags="Trunk")
      System(yegMiridor01DB, "Postgresql Container", $tags="lxdContainer")
      System(yegMiridor01Suricata, "IDS Container", $tags="lxdContainer")
      Rel_D(yegMiridor01, yegMiridor01DB, "", $tags="VLANBridge")
      Rel_D(yegMiridor01, yegMiridor01Suricata, "", $tags="VLANBridge")
      Rel_D(yegMiridor01, yegMiridor01Suricata, "", $tags="IntMirror")
    System(yegMiridor02, "LXD Host\nyeg-miridor-02", $tags="bareMetal")
    Rel_D(yegSwitch, yegMiridor02, "", $tags="VLANMirror")
    Rel_D(yegSwitch, yegMiridor02, "", $tags="Trunk")
      System(yegMiridor02DB, "Postgresql Container", $tags="lxdContainer")
      System(yegMiridor02Suricata, "IDS Container", $tags="lxdContainer")
      Rel_D(yegMiridor02, yegMiridor02DB, "", $tags="VLANBridge")
      Rel_D(yegMiridor02, yegMiridor02Suricata, "", $tags="VLANBridge")
      Rel_D(yegMiridor02, yegMiridor02Suricata, "", $tags="IntMirror")
}
Rel_L(backbone, yegSwitch, "", $tags="Trunk")
Boundary(yycBoundary, "Calgary Datacenter", $tags="region")  {
  System(yycSwitch, "Distribution Switch", $tags="network")
    System(yycMiridor01, "LXD Host\nyyc-miridor-01", $tags="bareMetal")
    Rel_D(yycSwitch, yycMiridor01, "", $tags="VLANMirror")
    Rel_D(yycSwitch, yycMiridor01, "", $tags="Trunk")
      System(yycMiridor01DB, "Postgresql Container", $tags="lxdContainer")
      System(yycMiridor01Suricata, "IDS Container", $tags="lxdContainer")
      Rel_D(yycMiridor01, yycMiridor01DB, "", $tags="VLANBridge")
      Rel_D(yycMiridor01, yycMiridor01Suricata, "", $tags="VLANBridge")
      Rel_D(yycMiridor01, yycMiridor01Suricata, "", $tags="IntMirror")
    System(yycMiridor02, "LXD Host\nyyc-miridor-02", $tags="bareMetal")
    Rel_D(yycSwitch, yycMiridor02, "", $tags="VLANMirror")
    Rel_D(yycSwitch, yycMiridor02, "", $tags="Trunk")
      System(yycMiridor02DB, "Postgresql Container", $tags="lxdContainer")
      System(yycMiridor02Suricata, "IDS Container", $tags="lxdContainer")
      Rel_D(yycMiridor02, yycMiridor02DB, "", $tags="VLANBridge")
      Rel_D(yycMiridor02, yycMiridor02Suricata, "", $tags="VLANBridge")
      Rel_D(yycMiridor02, yycMiridor02Suricata, "", $tags="IntMirror")
}
Rel_R(backbone, yycSwitch, "", $tags="Trunk")

Boundary(cybera, "Cybera Network Closet", $tags="region") {
  System(cyberaSwitch, "Distribution Switch", $tags="network")
    System(cyberaHost, "LXD Host", $tags="bareMetal")
    Rel_D(cyberaSwitch, cyberaHost, "", $tags="Trunk")
      System(cyberaPortal, "Client Portal\n(Django Server)", $tags="lxdContainer")
      System(cyberaCMDB, "CMDB\n(Netbox)", $tags="lxdContainer")
      Rel_D(cyberaHost, cyberaPortal, "", $tags="VLANBridge")
      Rel_D(cyberaHost, cyberaCMDB, "", $tags="VLANBridge")
}
Rel(backbone, cyberaSwitch, "", $tags="Trunk")

SHOW_LEGEND()

@enduml
